### ISSUE TITLE
Feature: User will be able to view the latest scores of a recent soccer match from the spanish league

### ISSUE THREAD

**Issue by joshuapreciado** [joshuapreciado/Ajax-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

**User will be able to view the latest scores of a recent soccer match from the spanish league**

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Use the API Football to use it's data
- [ ] Create a live-score card that will use JavaScript, HTML5, CSS3, to display the scoreboard
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
