### ISSUE TITLE
Feature: User can view a youtube video  from the most recent match in the league, via the youtube IFrameAPI

### ISSUE THREAD

**Issue by joshuapreciado** [joshuapreciado/Ajax-Project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a youtube video  from the most recent match in the league, via the [youtube IFrameAPI](https://developers.google.com/youtube/iframe_api_reference)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Integrate the Youtube API into the website with a highlight video from the most recent match that will match the current scoreboard of the match being displayed

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
